// Generated by https://quicktype.io

export interface ErrorCity {
  code: string;
  config: Config;
  message: string;
  name: string;
  stack: string;
  status: number;
}

export interface Config {
  transitional: Transitional;
  adapter: string[];
  transformRequest: null[];
  transformResponse: null[];
  timeout: number;
  xsrfCookieName: string;
  xsrfHeaderName: string;
  maxContentLength: number;
  maxBodyLength: number;
  env: Env;
  headers: Headers;
  method: string;
  url: string;
}

export interface Env {}

export interface Headers {
  Accept: string;
}

export interface Transitional {
  silentJSONParsing: boolean;
  forcedJSONParsing: boolean;
  clarifyTimeoutError: boolean;
}
